### PR TITLE
Update master to iDynTree v0.3

### PR DESCRIPTION
**Pull request by traversaro**
Big merge:
  * kdl_codyco and kdl_format_io are now part of the iDynTree repo,
  * a lot of update and fixes,
  * start of removing logic from the yarp classes.

### CODE REVIEW

**Comment by francesco-romano** [comment]
@traversaro  Can you wait a bit before merging?
I'm fixing compilation errors

**Comment by traversaro** [comment]
@francesco-romano ok

**Comment by francesco-romano** [comment]
@traversaro 
Ok. 

Tests do not compile, CMakes are a mess (and they build static libraries) but Core component can be compiled on OS X

**Comment by francesco-romano** [comment]
Now it should be better:
- libraries correctly compiled as shared.
- cleaned up  cmakes

If you want to wait for travis, for me it is ok to merge @traversaro

**Pull request merged**
